name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }} 'bash -se' <<'EOF'
            set -e

            # 1. Navigate to the project directory.
            cd ~/word_ban

            # 2. Pull the latest code.
            git pull

            # 3. Create virtual environment if it doesn’t exist.
            [ -d ".venv" ] || python3 -m venv .venv

            # 4. Install dependencies.
            .venv/bin/python -m pip install -r requirements.txt

            # 5. Set up systemd user service
            mkdir -p ~/.config/systemd/user

            cat > ~/.config/systemd/user/slack-bot.service <<'EOL'
            [Unit]
            Description=Word BAN Slack Bot

            [Service]
            WorkingDirectory=%h/word_ban
            EnvironmentFile=%h/word_ban/.env
            ExecStart=%h/word_ban/.venv/bin/python app.py
            Restart=on-failure

            [Install]
            WantedBy=default.target
            EOL

            # 6. Enable lingering and start service
            loginctl enable-linger "$(whoami)" || true
            systemctl --user daemon-reexec || true
            systemctl --user daemon-reload
            systemctl --user enable --now slack-bot.service
          EOF