name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses:  webfactory/ssh-agent@v0.9.0
        with:
           ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USER }}@${{ secrets.NEST_HOST }} '
            set -e
            # Navigate to the project directory using an absolute path for reliability
            cd word_ban
            
            # Pull the latest code
            git pull
            
            # Install dependencies using a relative path from the project root
            ./.venv/bin/pip install -r requirements.txt
            
            # Restart the service
            sudo systemctl restart slack-bot.service
          '

