name: Deploy to Server

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          # Copy the deploy script to the server and then execute it.
          scp -o StrictHostKeyChecking=no ./deploy.sh ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }}:/home/spacexplorer11/word_ban/
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }} /home/spacexplorer11/word_ban/deploy.sh
