name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          # This command connects to the server and executes a new bash shell.
          # The -c flag tells bash to read commands from the following string.
          # This ensures all commands run in the same, reliable context.
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }} \
          'bash -c "
            set -e
            
            # 1. Navigate to the project directory.
            cd /home/spacexplorer11/word_ban
            
            # 2. Pull the latest code.
            git pull
            
            # 3. Create virtual environment if it doesn’t exist.
            if [ ! -d \".venv\" ]; then
              python3 -m venv .venv
            fi
            
            # 4. Install dependencies using the venv’s python to run pip.
            ./.venv/bin/python -m pip install -r requirements.txt
            
            # 5. Stop and start the bot process.
            screen -S slack-bot -X quit || true
            screen -dmS slack-bot ./.venv/bin/python app.py
          "'