name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }} '
            set -e
            
            # 1. Navigate to the project directory using its absolute path.
            cd /home/spacexplorer11/word_ban
            
            # 2. Pull the latest code.
            git pull
            
            # 3. Create virtual environment if it doesn't exist.
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi
            
            # 4. Install dependencies using ABSOLUTE paths for reliability.
            /home/spacexplorer11/word_ban/.venv/bin/pip install -r /home/spacexplorer11/word_ban/requirements.txt
            
            # 5. Stop the old bot process.
            screen -S slack-bot -X quit || true
            
            # 6. Start the new bot process using ABSOLUTE paths.
            screen -dmS slack-bot /home/spacexplorer11/word_ban/.venv/bin/python /home/spacexplorer11/word_ban/app.py
          '
