name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }} '
            set -e
            
            # 1. Navigate to the project directory.
            cd word_ban
            
            # 2. Pull the latest code.
            git pull
            
            # 3. Create virtual environment if it doesn't exist.
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi
            
            # 4. Install/update dependencies.
            ./.venv/bin/pip install -r requirements.txt
            
            # 5. Stop the old bot process if it's running in a screen session.
            # The `|| true` prevents an error if the session doesn't exist.
            screen -S slack-bot -X quit || true
            
            # 6. Start the new bot process in a new, detached screen session.
            screen -dmS slack-bot ./.venv/bin/python app.py
          '