name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.NEST_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.NEST_USERNAME }}@${{ secrets.NEST_HOST }} \
          'bash -c "
            set -e
            
            # 1. Navigate to the project directory.
            cd /home/spacexplorer11/word_ban
            
            # 2. Pull the latest code.
            git pull
            
            # 3. Create virtual environment if it doesn’t exist.
            if [ ! -d \".venv\" ]; then
              python3 -m venv .venv
            fi
            
            # 4. Install dependencies.
            ./.venv/bin/python -m pip install -r requirements.txt
            
            # 5. Stop any old bot processes using pkill for reliability.
            # The -f flag matches the full command string. `|| true` prevents an error if no process is found.
            pkill -f \"app.py\" || true
            
            # 6. Start the new bot process in a detached screen session.
            screen -dmS slack-bot ./.venv/bin/python app.py
          "'